ros2_serializer:
    ros__parameters:
        chatter:
            serial_mapping: 9
            type: std_msgs/String
        different:
            serial_mapping: 12
            type: std_msgs/String
